/**
 * Maps error types to concrete SKILL.md patch content.
 * Each patch is a markdown section that gets injected into the skill template
 * to address a specific failure pattern found in telemetry.
 */

export interface PatchTemplate {
  id: string;
  skill: string;
  title: string;
  content: string;
}

/**
 * Generate patch markdown for a given skill + error type combination.
 * Returns null if no patch template exists for this combination.
 */
export function getPatchContent(
  skill: string,
  errorType: string,
  evidence: string,
  patchId: string,
): PatchTemplate | null {
  const key = `${skill}:${errorType}`;

  const templates: Record<string, () => PatchTemplate> = {
    // ─── QA skill patches ────────────────────────────────────
    "qa:timeout": () => ({
      id: patchId,
      skill,
      title: "Pre-check: Dev Server Connectivity",
      content: `### Pre-check: Dev Server Connectivity

> Auto-evolved from telemetry: ${evidence}

Before launching browser-based QA tests, verify the dev server is responding.
If the server is not running, prompt the user to start it before proceeding.

\`\`\`bash
_DEV_PORT=\$(grep -rE 'PORT|port' .env .env.local 2>/dev/null | head -1 | grep -oE '[0-9]{4,5}' || echo "3000")
if ! curl -sf "http://localhost:\$_DEV_PORT" >/dev/null 2>&1; then
  echo "WARNING: Dev server not responding on port \$_DEV_PORT"
  echo "Start it before running QA tests."
fi
\`\`\``,
    }),

    "qa:scope_exceeded": () => ({
      id: patchId,
      skill,
      title: "QA Scope Limiter",
      content: `### QA Scope Limiter

> Auto-evolved from telemetry: ${evidence}

Limit QA testing to the specific feature or page under test.
Do not expand scope beyond what was requested. If more than 5 pages need testing,
ask the user to confirm before proceeding.`,
    }),

    // ─── Investigate skill patches ───────────────────────────
    "investigate:scope_exceeded": () => ({
      id: patchId,
      skill,
      title: "Time-Budget Checkpoint",
      content: `### Time-Budget Checkpoint

> Auto-evolved from telemetry: ${evidence}

At the midpoint of investigation (after Phase 2), check elapsed time.
If the investigation has been running for more than 10 minutes:
1. Stop exploring new hypotheses
2. Rank existing hypotheses by evidence strength
3. Commit to the top hypothesis and proceed to verification
4. If no strong hypothesis exists, escalate to the user

Do not continue unbounded investigation past 10 minutes.`,
    }),

    "investigate:timeout": () => ({
      id: patchId,
      skill,
      title: "Investigation Timeout Guard",
      content: `### Investigation Timeout Guard

> Auto-evolved from telemetry: ${evidence}

Before starting deep investigation:
1. Set a 15-minute time budget
2. At 10 minutes, force-rank hypotheses
3. At 15 minutes, report best hypothesis even if unconfirmed
4. Never silently timeout. Always produce a finding.`,
    }),

    // ─── Review skill patches ────────────────────────────────
    "review:false_positive": () => ({
      id: patchId,
      skill,
      title: "ORM-Aware SQL Safety Check",
      content: `### ORM-Aware SQL Safety Check

> Auto-evolved from telemetry: ${evidence}

Before flagging SQL injection warnings, detect if the project uses an ORM:

\`\`\`bash
_ORM_DETECTED=""
grep -qE '"prisma"|"drizzle"|"typeorm"|"sequelize"|"@mikro-orm"' package.json 2>/dev/null && _ORM_DETECTED="node"
grep -qE 'sqlalchemy|django\\.db|activerecord' requirements.txt Gemfile 2>/dev/null && _ORM_DETECTED="other"
\`\`\`

If an ORM is detected, skip SQL injection warnings on:
- Query builder patterns (e.g., \`.where()\`, \`.findMany()\`, \`.select()\`)
- Parameterized queries generated by the ORM
- Migration files

Only flag raw SQL strings that bypass the ORM entirely.`,
    }),

    "review:parse_error": () => ({
      id: patchId,
      skill,
      title: "Diff Parse Fallback",
      content: `### Diff Parse Fallback

> Auto-evolved from telemetry: ${evidence}

If the diff output cannot be parsed (binary files, encoding issues, very large diffs):
1. Fall back to file-level analysis instead of line-level
2. Read changed files directly instead of parsing the diff
3. Report which files could not be diffed and why`,
    }),

    // ─── Ship skill patches ──────────────────────────────────
    "ship:ci_failure": () => ({
      id: patchId,
      skill,
      title: "Pre-flight Lint Check",
      content: `### Pre-flight Lint Check

> Auto-evolved from telemetry: ${evidence}

Before creating a PR, run the project's lint and type-check commands:

\`\`\`bash
# Detect and run lint
if [ -f package.json ]; then
  npm run lint 2>/dev/null || npx eslint . 2>/dev/null || true
  npx tsc --noEmit 2>/dev/null || true
fi
\`\`\`

If lint fails, fix the issues before proceeding with the PR.`,
    }),

    // ─── Generic fallback patches ────────────────────────────
    "generic:timeout": () => ({
      id: patchId,
      skill,
      title: "Connectivity Pre-check",
      content: `### Connectivity Pre-check

> Auto-evolved from telemetry: ${evidence}

Before network-dependent operations, verify the target is reachable.
If a timeout occurs during execution, retry once with a longer timeout
before reporting failure.`,
    }),

    "generic:general_failure": () => ({
      id: patchId,
      skill,
      title: "Error Recovery",
      content: `### Error Recovery

> Auto-evolved from telemetry: ${evidence}

If this skill encounters an unexpected error:
1. Log the error details for telemetry
2. Attempt a single retry with a clean state
3. If retry fails, report the error clearly and escalate`,
    }),
  };

  // Try skill-specific first, then generic
  const factory = templates[key] || templates[`generic:${errorType}`];
  return factory ? factory() : null;
}

/**
 * Get all available error types that have patch templates.
 */
export function getAvailablePatches(): string[] {
  return [
    "timeout", "scope_exceeded", "false_positive",
    "parse_error", "ci_failure", "general_failure",
  ];
}
